### ISSUE TITLE
First test indicator available

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/adriaclim-geoportal#13]
An indicator with yearly data has been uploaded to Erddap, it is a "table" dataset "TEST Indicator wsdi, MedCordex (LMDZ), yearly, 2021-2050, Puglia". The geoportal sees it, but nothing happens if I select it. Although not definitive (e.g. the dates should point to 01/01 not 07/01) we can start working on it.

**Comment by fraFerrari99** [comment]
Hi Davide, there are some problems about it. 

Now when I select it, it is attached to the map with our WMS, but there are some problems with the graphics due to the lack of data for a specific point of the dataset. For example if you click on a point of the map where the dataset is displayed, very surely will throw an error due to this lack of data. 

So what I wanted to do, at least for now, was, instead of throwing an error, show by default the flow of all the available points of the dataset, like we do now in polygon graphics.

Can this be a valid solution?
